version: '3.1'

services:
    app:
        image: miahal7/simple-ledger:0.0.1
        volumes:
          - ~/config/nginx/app-server.conf:/etc/nginx/sites-enabled/app-server.conf
        links:
            - db
    db:
        image: mongo:3.4.6
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ~/data/db:/data/db
        ports:
            - 27017:27017
    proxy:
        image: nginx
        ports:
            - 443:443
        volumes:
            - ~/config/certs/simple-ledger.crt:/etc/nginx/simple-ledger.crt
            - ~/config/certs/simple-ledger.key:/etc/nginx/simple-ledger.key
            - ~/config/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
