version: '3'

services:
    app:
        image: miahal7/simple-ledger:0.0.1
        links:
            - db
    db:
        image: mongo:3.4.6
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ~/data/db:/data/db
        ports:
            - 27017:27017
    proxy:
        image: nginx
        ports:
            - "8090:80"
        volumes:
            - "${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - app
